server:
  port: 8089
  servlet:
    context-path: /api


limit:
  minMoney: 1
  maxMoney: 999
  desc: 最小“${limit.minMoney}”, 最大"${limit.maxMoney}"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/money
    username: root
    password: keyu0102
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
mytablename: luckmoney

